config/routes.rb
Rails.application.routes.draw do

  get '/profile' => 'users#show'

  get '/profile/edit' => 'registration#edit'

  get '/about' => 'users#about'
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}


  resources :cities do
    resources :posts do
      resources :comments
    end
  end

  # # ----> THIS WILL DO ALL ROUTES WELL.
  #
  #
  # get '/' => 'cities#index' # list all cities page
  #
  # get '/cities' => 'cities#index', as: 'city'
  # get '/cities/:id' => 'cities#show', as: 'show'
  # #
  # get '/cities/:city_id/posts/new' => 'posts#new', as: 'new'
  # #
  # # post '/cities/:city_id/' => 'posts#create'
  # #
  # post '/cities/:id/posts' => 'posts#create', as: 'posts'
  # #
  # get '/cities/:city_id/posts/:id' => 'posts#show', as: 'post_show'
  # #
  # get '/cities/:city_id/posts/:id/edit' => 'posts#edit', as: 'edit'
  # #
  # put '/cities/:city_id/posts/:id' => 'posts#update'
  # #
  # delete '/cities/:id' => 'posts#destroy', as: 'post'



  # ADDED for root
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :comments
  # validates_length_of :title, :minimum=>1, :message=>"put something here"
  # validates_length_of :title, :maximum=>200, :message=>"less than 200 characters please"
  validates :title, length: { within: 1..200 }
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def show
    @post = Post.find(params[:id])
    @city = @post.city_id
    @user = @post.user
    @city_object = @post.city
    @comments = @post.comments
    

  end

  def new
    @city = City.find(params[:city_id])
    @post = Post.new
  end

  def create
    post = Post.create(post_params)
    city = City.find(params[:city_id])
    validate_new_post(post)
  end

  def edit
    @post = Post.find(params[:id])
    @city = @post.city
    # redirect_to city_post_path(@city, @post)
  end

  def update
    post = Post.find(params[:id])
    city = City.find(params[:city_id])
    post.update(post_params)
    redirect_to city_post_path(city, post)
  end

  def destroy
    @post = Post.find(params[:id])
    city_id = @post.city_id
    @post.destroy
    redirect_to city_path(city_id)
  end
  
  private
  def post_params
    params.require(:post)
      .permit(:title, :content)
      .merge(user_id: current_user.id, city_id: params[:city_id])
  end
  def validate_new_post(post)
    city = City.find(params[:city_id])
    if post.errors.any?
      error_object = post.errors.messages.keys.first.to_s
      error_message = post.errors.messages.values.first[0].to_s
      flash[:errors] = error_object.capitalize + " " + error_message
      redirect_to :back
    else
      redirect_to city_path(city)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<!-- breadcrumb nav -->

<!-- 
<div class='test' style="background-image: url('<%= @city.image_url %>')"></div> -->

<!-- <div><img src="<%= @city.image_url %>"></div> -->


  <nav>
    <div class="nav-wrapper sub-nav">
      <div class="col s12">
        <span href="#!" class="breadcrumb"> <%= link_to 'All Cities', cities_path %> </span>
        <span class="breadcrumb"><%= link_to @city.name, city_path(@city.id) %> </span>
        <a href="#!" class="breadcrumb"><%= link_to @post.title, city_post_path(@city.id, @post.id) %></a>
      </div>
    </div>
  </nav>

<div class="container">
  <div class="card form_card">
      <p>
        <% link_to 'back to city', @city %>
      </p>

      <h1 class="page-main-header center"> Edit Post </h1>

      <%= form_for [@city, @post] do |f| %>
        <p>
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </p>
        <p>
          <%= f.label :content %><br>
          <%= f.text_area :content,  :rows => 50 %>
        </p>

        <p>
          <%= f.submit "Update" ,class: "btn btn-primary project-btn right" %>
        </p>
        <br>
        <br>
      <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<!-- Add New Post Page -->
  <nav>
    <div class="nav-wrapper sub-nav">
      <div class="col s12">
        <span href="#!" class="breadcrumb"> <%= link_to 'View cities', cities_path %> </span>
        <span class="breadcrumb"><%= link_to @city.name, @city %> </span>
        <a href="#!" class="breadcrumb">New Post</a>
      </div>
    </div>
  </nav>

<div class="container">
  <div class="card form_card">
  <!-- back link -->
    <p><% link_to 'back to city', @city %></p>

    <h1 class="page-main-header center"> Add new post </h1>
    <!-- Form for new post -->
    <%= form_for [@city, @post] do |f| %>
  
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    
    <p>  
      <%= f.label :content %><br>
      <%= f.text_field :content %>
    </p>

    <p>
      <%= f.submit :class=> "waves-effect waves-light btn btn-large add-post-button right"%>
    </p>
  
    <% if flash[:errors] %>
      <h5 class="error-message-red"><%= flash[:errors] %></h5>
    <% end %>
      <br>
      <br>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
  
<!-- Breadcrumb nav -->
  <nav>
    <div class="nav-wrapper sub-nav">
      <div class="col s12">
        <span href="#!" class="breadcrumb"> <%= link_to 'All Cities', cities_path %> </span>
        <span class="breadcrumb"><%= link_to @city_object.name, city_path(@city) %> </span>
        <a  class="breadcrumb"> <%= @post.title %> </a>        
      </div>
    </div>
  </nav>

    <div class="container">
      <div class="card form_card">
        <h3 class="page-main-header center"><%= @post.title %></h3>
        <% if @post.user_id == current_user.id %>
        <%= link_to "Edit Post",  edit_city_post_path(@post), class: "btn btn-primary project-btn right" %>
        <% end %>

        <p class="secondary-font"><%= @post.content %></p>
        <%= link_to 'Add Comment', new_city_post_comment_path(@city, @post), class: "btn-mini btn btn-primary btn-small green lighten-3 left"%>
        <br>
        <br>
        <% @comments.each do |comment| %>
          <div class="card form_card">
            <p> "<%= comment.content %>" </p>
            <p><small> - <%= comment.user.name %></small></p>
            <% if comment.user_id == current_user.id%>
              <%= link_to 'Delete comment', city_post_comment_path(@city, @post, comment), method: :delete, data: {confirm: "Are you sure?"}, class: "right btn-mini btn btn-primary btn-small red lighten-3"%><br><br>
            <% end %>
          </div>
        <% end %>
      </div>  
    </div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>