config/routes.rb
Rails.application.routes.draw do

  get '/profile' => 'users#show'

  get '/profile/edit' => 'registration#edit'

  get '/about' => 'users#about'
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}


  resources :cities do
    resources :posts do
      resources :comments
    end
  end

  # # ----> THIS WILL DO ALL ROUTES WELL.
  #
  #
  # get '/' => 'cities#index' # list all cities page
  #
  # get '/cities' => 'cities#index', as: 'city'
  # get '/cities/:id' => 'cities#show', as: 'show'
  # #
  # get '/cities/:city_id/posts/new' => 'posts#new', as: 'new'
  # #
  # # post '/cities/:city_id/' => 'posts#create'
  # #
  # post '/cities/:id/posts' => 'posts#create', as: 'posts'
  # #
  # get '/cities/:city_id/posts/:id' => 'posts#show', as: 'post_show'
  # #
  # get '/cities/:city_id/posts/:id/edit' => 'posts#edit', as: 'edit'
  # #
  # put '/cities/:city_id/posts/:id' => 'posts#update'
  # #
  # delete '/cities/:id' => 'posts#destroy', as: 'post'



  # ADDED for root
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/city.rb
class City < ApplicationRecord
  has_many :posts
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    # display all cities on index page
    @cities = City.all

  end

  def show
    @city = City.find(params[:id])
    @posts = @city.posts
    @ordered_posts = @posts.order( 'updated_at DESC')
  end


end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="center city-name letter-spacing">CITIES</h1>
    </div>
      <% @cities.each do |city| %>

      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a href='<%="/cities/#{city.id}"%>'>
          <img class="img-responsive" <%= image_tag city.image_url %><p class="text-center"><%= link_to "#{city.name}", city_path(city.id), :class=> "secondary-font" %></p>
        </a>
      </div>
      <% end %>
  </div>
</div>

app/views/cities/show.html.erb
<!-- City Show Page -->
<div class='img-container'>
  <h1 class="center city-name"><%= @city.name %></h1>
  <img class="img-responsive center city-picture" <%=  image_tag @city.image_url %>
</div>

<div class="container">
  <div class="margin-around"><%= link_to "Add Post", new_city_post_path(@city), class: "waves-effect waves-light btn btn-large add-post-button right"%></div>
  
  <!-- All posts posted on particular City show page -->
  <% @ordered_posts.each do |post| %>
    <div class="margin-top card projCard col-lg-4 center">
      <div class="card-block">
        <h4 class="card-title post-title"><%= link_to post.title, city_post_path(@city, post)%></h4>
          <hr class="small">
        <p class="secondary-font card-text"> <%=h truncate(post.content, :length => 1000) %></p>
        <%= link_to "see more", city_post_path(@city, post), class: "btn btn-primary project-btn"%>
        <br>
        <br>

        <div class="right">
          <br>
          <i> created <%= time_ago_in_words(post.created_at) %> ago </i>
          <br>
          <i> updated <%= time_ago_in_words(post.updated_at) %> ago </i>
          <br>
          <% if post.user_id == current_user.id%>
          <%= link_to 'Delete post', city_post_path(@city, post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn-mini btn btn-primary btn-small red lighten-3 right"%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>