config/routes.rb
Rails.application.routes.draw do

  get '/profile' => 'users#show'

  get '/profile/edit' => 'registration#edit'

  get '/about' => 'users#about'
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}


  resources :cities do
    resources :posts do
      resources :comments
    end
  end

  # # ----> THIS WILL DO ALL ROUTES WELL.
  #
  #
  # get '/' => 'cities#index' # list all cities page
  #
  # get '/cities' => 'cities#index', as: 'city'
  # get '/cities/:id' => 'cities#show', as: 'show'
  # #
  # get '/cities/:city_id/posts/new' => 'posts#new', as: 'new'
  # #
  # # post '/cities/:city_id/' => 'posts#create'
  # #
  # post '/cities/:id/posts' => 'posts#create', as: 'posts'
  # #
  # get '/cities/:city_id/posts/:id' => 'posts#show', as: 'post_show'
  # #
  # get '/cities/:city_id/posts/:id/edit' => 'posts#edit', as: 'edit'
  # #
  # put '/cities/:city_id/posts/:id' => 'posts#update'
  # #
  # delete '/cities/:id' => 'posts#destroy', as: 'post'



  # ADDED for root
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!-- Layout Page -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>DriftR</title>
    <%= csrf_meta_tags %>
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Materialize -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <!-- Custom style -->
    <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/application.css">
    <link rel="stylesheet" type="text/css" href= Rails.root + "/app/assets/stylesheets/posts.scss">
    <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/cities.scss">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister|Open+Sans" rel="stylesheet">

<!-- Rails.root + '/app/assets/...' -->
  </head>
  <body>
  <!-- navbar -->
    <nav class="teal accent-4">
      <div class="nav-wrapper">
        <a href="/"><img src="http://i.imgur.com/NwOxEso.png" style="width:50px; margin: -20px 0px 0 5px">
        <span class="logotype">DriftR</span></a>
        <ul class="right hide-on-med-and-down">

          <!-- If user signed in, they're able to view cities -->
          <% if user_signed_in? %>
            <% if user_signed_in? && @city %>
              <li><%= link_to 'Add new post', new_city_post_path(@city) %></li>
            <% end %>
              <li><%= link_to 'View cities', cities_path %></li>
              <li><%= link_to 'Profile', profile_path %></li>
              <li><a href="/about"> About Us </a></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
          <% else %>
          <!-- if user is not signed in, they can only sign up or sign in or view contacts -->
    	        <li><%= link_to "Sign Up", new_user_registration_path %></li>
    	        <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><a href="/about"> About Us</a></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
  </body>
</html>